# Generated by Django 4.2.11 on 2024-03-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_editting',
            field=models.BooleanField(default=False),
        ),
    ]
